name: Release waylonwalker

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

env:
  HATCH_INDEX_USER: __token__
  HATCH_INDEX_AUTH: ${{ secrets.pypi_password }}

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - uses: waylonwalker/hatch-action@v2
        with:
          before-command: "lint"
