name: Release waylonwalker

on:
  workflow_dispatch:
  push:
    paths:
      - "waylonwalker/**"
      - "pyproject.toml"

env:
  HATCH_INDEX_USER: __token__
  HATCH_INDEX_AUTH: ${{ secrets.pypi_password }}

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: waylonwalker/hatch-action@v3
        with:
          before-command: "lint"
